-- ============================================================================
-- 100% SAFE MIGRATION SCRIPT - ADD FIELDS ONLY (ZERO DATA DELETION)
-- This script ONLY adds missing columns and tables without dropping or deleting data.
-- ============================================================================

-- 1. Ensure Purchase & PO detail tables have Rate and Premium fields
ALTER TABLE IF EXISTS purchase_detail_master ADD COLUMN IF NOT EXISTS rate_qntl NUMERIC(15,2) DEFAULT 0;
ALTER TABLE IF EXISTS purchase_detail_master ADD COLUMN IF NOT EXISTS premium NUMERIC(15,2) DEFAULT 0;

ALTER TABLE IF EXISTS temporary_po_details ADD COLUMN IF NOT EXISTS rate_qntl NUMERIC(15,2) DEFAULT 0;
ALTER TABLE IF EXISTS temporary_po_details ADD COLUMN IF NOT EXISTS premium NUMERIC(15,2) DEFAULT 0;

ALTER TABLE IF EXISTS sauda_check_point_details ADD COLUMN IF NOT EXISTS rate_qntl NUMERIC(15,2) DEFAULT 0;
ALTER TABLE IF EXISTS sauda_check_point_details ADD COLUMN IF NOT EXISTS premium NUMERIC(15,2) DEFAULT 0;

ALTER TABLE IF EXISTS purchase_master ADD COLUMN IF NOT EXISTS premium NUMERIC(15,2) DEFAULT 0;
ALTER TABLE IF EXISTS sauda_check_point ADD COLUMN IF NOT EXISTS premium NUMERIC(15,2) DEFAULT 0;
ALTER TABLE IF EXISTS sauda_quality_details ADD COLUMN IF NOT EXISTS premium NUMERIC(15,2) DEFAULT 0;

-- 2. Ensure Payment Master table exists and has all columns
CREATE TABLE IF NOT EXISTS payment_master (
    payment_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    voucher_no TEXT UNIQUE NOT NULL,
    voucher_date DATE,
    financial_year TEXT,
    payment_date DATE,
    mr_no TEXT,
    mr_date DATE,
    arrival_no TEXT,
    arrival_date DATE,
    po_no TEXT,
    po_date DATE,
    supplier TEXT,
    party_name TEXT,
    broker TEXT,
    arrival_area TEXT,
    total_packets NUMERIC(15,2) DEFAULT 0,
    total_weight NUMERIC(15,3) DEFAULT 0,
    b_rate NUMERIC(15,2) DEFAULT 0,
    premium NUMERIC(15,2) DEFAULT 0,
    gross_amount NUMERIC(15,2) DEFAULT 0,
    sett_amount NUMERIC(15,2) DEFAULT 0,
    deduction_amount NUMERIC(15,2) DEFAULT 0,
    total_amount NUMERIC(15,2) DEFAULT 0,
    payable_amt NUMERIC(15,2) DEFAULT 0,
    paid_amount NUMERIC(15,2) DEFAULT 0,
    net_amt NUMERIC(15,2) DEFAULT 0,
    tds_amt NUMERIC(15,2) DEFAULT 0,
    claim_amount NUMERIC(15,2) DEFAULT 0,
    status TEXT DEFAULT 'Completed',
    remarks TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

ALTER TABLE IF EXISTS payment_master ADD COLUMN IF NOT EXISTS premium NUMERIC(15,2) DEFAULT 0;
ALTER TABLE IF EXISTS payment_master ADD COLUMN IF NOT EXISTS total_packets NUMERIC(15,2) DEFAULT 0;
ALTER TABLE IF EXISTS payment_master ADD COLUMN IF NOT EXISTS total_weight NUMERIC(15,3) DEFAULT 0;
ALTER TABLE IF EXISTS payment_master ADD COLUMN IF NOT EXISTS b_rate NUMERIC(15,2) DEFAULT 0;

-- 3. Ensure Payment Details table exists and has all breakdown fields
CREATE TABLE IF NOT EXISTS payment_details (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_id UUID REFERENCES payment_master(payment_id) ON DELETE CASCADE,
    voucher_no TEXT,
    mr_no TEXT,
    col_index INTEGER,
    grade TEXT,
    area TEXT,
    agency TEXT,
    marka_crop TEXT,
    quantity NUMERIC(15,2) DEFAULT 0,
    arr_qty_wt NUMERIC(15,3) DEFAULT 0,
    min_qty_wt NUMERIC(15,3) DEFAULT 0,
    wt_phota NUMERIC(15,3) DEFAULT 0,
    wt_quantity NUMERIC(15,3) DEFAULT 0,
    rate_value NUMERIC(15,2) DEFAULT 0,
    premium NUMERIC(15,2) DEFAULT 0,
    sett_pct NUMERIC(15,2) DEFAULT 0,
    deduction_rate NUMERIC(15,2) DEFAULT 0,
    sett_rate NUMERIC(15,2) DEFAULT 0,
    quantity_qtl NUMERIC(15,3) DEFAULT 0,
    amount NUMERIC(15,2) DEFAULT 0,
    gd_claim NUMERIC(15,2) DEFAULT 0,
    gd_sett NUMERIC(15,2) DEFAULT 0,
    gd_rev NUMERIC(15,2) DEFAULT 0,
    gd_final NUMERIC(15,2) DEFAULT 0,
    moist_claim NUMERIC(15,2) DEFAULT 0,
    moist_sett NUMERIC(15,2) DEFAULT 0,
    moist_rev NUMERIC(15,2) DEFAULT 0,
    moist_final NUMERIC(15,2) DEFAULT 0,
    dust_claim NUMERIC(15,2) DEFAULT 0,
    dust_sett NUMERIC(15,2) DEFAULT 0,
    dust_rev NUMERIC(15,2) DEFAULT 0,
    dust_final NUMERIC(15,2) DEFAULT 0,
    ncv_claim NUMERIC(15,2) DEFAULT 0,
    ncv_sett NUMERIC(15,2) DEFAULT 0,
    ncv_rev NUMERIC(15,2) DEFAULT 0,
    ncv_final NUMERIC(15,2) DEFAULT 0,
    po_grade_claim NUMERIC(15,2) DEFAULT 0,
    po_grade_sett NUMERIC(15,2) DEFAULT 0,
    po_grade_rev NUMERIC(15,2) DEFAULT 0,
    po_grade_final NUMERIC(15,2) DEFAULT 0,
    adjust_type TEXT,
    remark TEXT,
    claim_settlement NUMERIC(15,2) DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

ALTER TABLE IF EXISTS payment_details ADD COLUMN IF NOT EXISTS premium NUMERIC(15,2) DEFAULT 0;
ALTER TABLE IF EXISTS payment_details ADD COLUMN IF NOT EXISTS sett_rate NUMERIC(15,2) DEFAULT 0;
ALTER TABLE IF EXISTS payment_details ADD COLUMN IF NOT EXISTS deduction_rate NUMERIC(15,2) DEFAULT 0;
ALTER TABLE IF EXISTS payment_details ADD COLUMN IF NOT EXISTS sett_pct NUMERIC(15,2) DEFAULT 0;
ALTER TABLE IF EXISTS payment_details ADD COLUMN IF NOT EXISTS rate_value NUMERIC(15,2) DEFAULT 0;
ALTER TABLE IF EXISTS payment_details ADD COLUMN IF NOT EXISTS quantity_qtl NUMERIC(15,3) DEFAULT 0;
ALTER TABLE IF EXISTS payment_details ADD COLUMN IF NOT EXISTS amount NUMERIC(15,2) DEFAULT 0;

-- 4. Open Remarks columns
ALTER TABLE IF EXISTS sauda_check_point ADD COLUMN IF NOT EXISTS open_remarks JSONB;
ALTER TABLE IF EXISTS sauda_master ADD COLUMN IF NOT EXISTS open_remarks JSONB;
ALTER TABLE IF EXISTS purchase_master ADD COLUMN IF NOT EXISTS open_remarks JSONB;

-- 5. Safe indexing
CREATE INDEX IF NOT EXISTS idx_sauda_status_created ON sauda_master(status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_sauda_check_point_po_status ON sauda_check_point(po_no, status);
CREATE INDEX IF NOT EXISTS idx_purchase_master_po_status ON purchase_master(po_no, status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_purchase_detail_po_grade ON purchase_detail_master(po_no, grade_code);
CREATE INDEX IF NOT EXISTS idx_payment_master_supp_po ON payment_master(supplier, po_no, mr_no);
CREATE INDEX IF NOT EXISTS idx_payment_details_voucher ON payment_details(voucher_no, mr_no);
